Repository GDSC-BSIOTR/About-webRepo-hacktoberfest-, pull requests merged in 2022-09, with the labels that each got.

#4 added line 23 to 34
  info.html
Labels: hacktoberfest, hacktoberfest-accepted

#8 added my info
  info.html
Labels: hacktoberfest, hacktoberfest-accepted

#9 added a css part pink
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#12 updated info h4
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hactober-accepeted

#13 i have added some html code in this repository
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hactober-accepeted

#14 updated with colour crimson
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hactober-accepeted

#11 updating info
  info.html
Labels: hacktoberfest, hacktoberfest-accepted

#10 Added about me
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#15 Commit
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#17 added info and updated
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#22 added my name info
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#23 Update info.html
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#24 updated h1
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#21 Added my Information
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#25 added my info
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#20 added info
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#26 updated info h1 (margin part)
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#28 Updated
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#27 added my information
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#29 updated my info
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#30 Commite
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#19 Updated
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#18 Commit
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#16 new.css
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#31 Commit
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#35 update
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#34 added info
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#36 Update info.html
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#37 Added Myself
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#38 Update info.html
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#39 something
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#40 Update info.html
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#41 Update info.html
  info.html
Labels: hacktober-accepted

#42 added info
  info.html
Labels: hacktoberfest-accepted, hacktober-accepted

#43 Update info.html
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#44 Update info.html
  info.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted
